### ISSUE TITLE
DOC: Add markdown table for supported Os

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#22]
## Goal
Create markdown table for supported os in readme.md  ( the table should not be complete a skeleton for this issue is enough)

# Tasks:

- [ ] Look at the example directory and search for the os we support. ( https://github.com/MalloZup/ceph-open-terrarium/tree/master/examples)

- [ ] In the Readme.md put a new section with a  Markdowntable with the OS we support.

Take a look here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

- [ ] Research on OS Linux distros , hint ( opensuse/centos7/fedora/ubuntu/debian/gentoo/)

- [ ] Important: don\t add all Os, just few of them and add the already OS present in the example dir

The table should be like
```
                     Implemented  Not Implemented yet            
Centos 7                  x
Opensuse423.
Opensuse15                                     x 
Archlinux
```
Etc , the goal of the table is to give a new comer which OS we might support and we could be open to support.

I this way we can extend the module and beeing more collaborative open about the example at first glance.

**Comment by MalloZup** [comment]
@craigthomas :heart:
