### ISSUE TITLE
add fedora module images

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#5]
# Goal:
add the openstack fedora images and test it works.

# Tasks:
Take latest fedora  cloude image. Following same structure as the centos, add an example.

- [ ] Create fedora module like centos7:
https://github.com/MalloZup/ceph-open-terrarium/tree/master/terraform/libvirt/images/centos

- [ ]  Adapt the needed variables

Add fedora example
- [ ] https://github.com/MalloZup/ceph-open-terrarium/blob/master/examples/centos.tf

**Comment by MalloZup** [comment]
Donw
